### ISSUE TITLE
replace to the error ? 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/kfp-operators#162]
https://github.com/canonical/kfp-operators/blob/17ee8b47528c782e4a871c76d53b3bff9504eb30/charms/kfp-api/src/charm.py#L306-L308

no human operator action could be performed

**Comment by i-chvets** [comment]
Done.
https://github.com/canonical/kfp-operators/blob/main/charms/kfp-api/src/charm.py#LL370-L373
