### ISSUE TITLE
Backport fixes to `track/2.0` from `main`

### ISSUE THREAD

**Issue by orfeas-k** [canonical/kfp-operators#341]
Following the effort that started here https://github.com/canonical/kfp-operators/issues/335 (see section `Suggested changes/backports`), we will need to backport those two good-to-have fixes to `track/2.0`.
- https://github.com/canonical/kfp-operators/commit/e87bb19f8a7afddd71c25eb604ed1c25a3535bf2
- https://github.com/canonical/kfp-operators/commit/4cef98ad6ca437accc28039876bd4dc61fe0690f

The rest of those in the list have already been backported

**Comment by NohaIhab** [comment]
there's no need to backport https://github.com/canonical/kfp-operators/commit/e87bb19f8a7afddd71c25eb604ed1c25a3535bf2 as we already specify the Controller service port in the PodSpec

**Comment by NohaIhab** [comment]
closing this since both commits don't need to backported to `track/2.0-alpha.7`
