### ISSUE TITLE
The recurring run does not work at kubeflow 1.17

### ISSUE THREAD

**Issue by emrahkyn** [canonical/kfp-operators#352]
### Bug Description

Hi Team,

I deployed a kubeflow 1.7 in test environment and was able to create a run without any issues. However, when I followed the similar procedure for recurring runs, it's created but never triggered to be executed. I could not get any error message, do you have any suggestions?
![image](https://github.com/canonical/kfp-operators/assets/76430580/4d2cd036-4f39-4e85-95b5-86d36d089830)

Thanks,
Emre

### To Reproduce

I deployed the kubeflow 1.7 by following the guideline [1] on kubernetes cluster and started to test it without doing any additional changes.

[1] https://charmed-kubeflow.io/docs/install

### Environment

It works on charmed kubernetes 1.28 with metallb load balancer.
[kfp-schedwf.log](https://github.com/canonical/kfp-operators/files/12915729/kfp-schedwf.log)
[kfp-api.log](https://github.com/canonical/kfp-operators/files/12915730/kfp-api.log)

### Relevant log output

```shell
The log files from kfp-api and kfp-schedwf pods are attached here. Please ignore the last part of the log files as I tried to create pipeline, experiments and run it manually using the kfp cli, but it did not work due to probably missing parameters.
```

### Additional context

I could not verify it yet but I've been informed that the recurring run does work at kubeflow 1.6 but after upgrade to 1.7, it started to not work.

**Comment by DnPlas** [comment]
Hi @emrahkyn thanks for reporting this. I was actually able to reproduce this issue, it seems like https://github.com/canonical/kfp-operators/pull/329 introduced an issue with the kfp-schedwf workload image.

As a workaround while we fix it you can deploy this component with `juju deploy kfp-schedwf --channel 1.7/stable --resource oci-image=gcr.io/ml-pipeline/scheduledworkflow:2.0.0-alpha.7`

cc: @i-chvets

**Comment by i-chvets** [comment]
Here are the findings:
- `kfp-schedwf` in 1.7 is PodSpec version.
- ROCKs were introduced (backported) to KFP pipelines for 1.7 #329 
- Container name in 1.7 `kfp-schedwf` charm differs from service name in ROCK:

Proposed solution:
- Change ROCK service name to match 1.7 container name. This will break `latest`, because service name != container name in sidecar version of `kfp-schedwf`. As a result, change service name to match container name in `main` OR create another version of ROCK for `main` (and 1.8).

**Comment by emrahkyn** [comment]
Hi @DnPlas and @i-chvets,

Thanks a lot for your help. I redeployed the kfp-schedwf application as you recommended, the recurring jobs are triggered to be executed now, however all of them failed with the following error message.

`This step is in Error state with this message: task 'execution-order-pipeline-zrht5.echo1-op' errored: admission webhook "admission-webhook.kubeflow.org" denied the request: poddefaults.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow:admission-webhook" cannot list resource "poddefaults" in API group "kubeflow.org" in the namespace "admin"`

Even I tried to execute a run (non-recurring), it gives the same error, I could not be sure it's related to specifically my deployment. When I deployed the previous version for kfp-schedwf application, the non-recurring runs started to work as it's previously.

**Comment by kimwnasptd** [comment]
@DnPlas @i-chvets looks like we have 2 independent issues here.
1. The ROCK is not working as expected
2. The ServiceAccount `system:serviceaccount:kubeflow:admission-webhook` doesn't have permissions to list PodDefaults (which is weird, since theoretically it should be the SA used by the PodDefaults webhook (?)

@emrahkyn could you also provide logs from the admission webhook pod in the `kubeflow` namespace?

Then, regarding the problematic ROCK, I see from the attached logs (thanks!) the following:
```
2023-10-13T09:29:08.022Z [controller] E1013 09:29:08.022113      15 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Workflow: failed to list *v1alpha1.Workflow: workflows.argoproj.io is forbidden: User "system:serviceaccount:kubeflow:kfp-schedwf" cannot list resource "workflows" in API group "argoproj.io" in the namespace "${NAMESPACE}"
```

There are 2 problems here:
1. The env var substitution has never happened https://github.com/canonical/pipelines-rocks/blob/main/scheduledworkflow/rockcraft.yaml#L16
2. The ROCK is wrong since we hardcode the `kubeflow` namespace, like it happened for Argo https://github.com/canonical/argo-operators/issues/143. In this case as well upstream sets this env var to `""` in order for the controller to monitor workflows from all namespaces

@i-chvets @DnPlas we need an issue to track the ROCK issue initially and then let's see what the issue will be with the admission webhook

**Comment by kimwnasptd** [comment]
@emrahkyn if you could also provide us with 
1. the ClusterRoles in your cluster (interested in the one that would be for the admission webhook)
2. The ClusterRoleBindings (again interested to see for the admission webhook)

It would really help us, as we are also looking into this in parallel

**Comment by emrahkyn** [comment]
Hi @kimwnasptd, 

Actually, I just followed the installation guideline [1] to deploy kubeflow 1.7 and nothing changed. If I did not do something wrong, it should be easy to reproduce. As this is a test environment, all machines and pods were down, but if you still need to get the requested information, I can redeploy it and provide all the requested information.

Meanwhile, I am not sure if it's related but I deployed it on kubernetes 1.28, and I could redeploy it on a older version?

[1]  https://charmed-kubeflow.io/docs/install

**Comment by DnPlas** [comment]
> Hi @kimwnasptd,
> 
> Actually, I just followed the installation guideline [1] to deploy kubeflow 1.7 and nothing changed. If I did not do something wrong, it should be easy to reproduce. As this is a test environment, all machines and pods were down, but if you still need to get the requested information, I can redeploy it and provide all the requested information.

It would be really helpful to have the requested ClusterRoles and ClusterRoleBindings, if you can provide them.

> 
> Meanwhile, I am not sure if it's related but I deployed it on kubernetes 1.28, and I could redeploy it on a older version?
> 
> [1] https://charmed-kubeflow.io/docs/install

We encourage people to stay within the boundaries of the [supported versions for each release](https://charmed-kubeflow.io/docs/supported-versions). While the CKF deployment may work in unsupported versions, there are specific workloads that won't work. In the case of CKF 1.7, we only support `1.22, 1.23, 1.24`.

**Comment by emrahkyn** [comment]
I will try to reproduce the issue on 1.24 and also provide all the requested information shortly.
Thanks

**Comment by DnPlas** [comment]
Just FYI. This is my environment:

* microk8s 1.24/stable
* juju 2.9/stable
* charmed kubeflow 1.7/stable
* I had to do the workaround: `juju deploy kfp-schedwf --channel 1.7/stable --resource oci-image=gcr.io/ml-pipeline/scheduledworkflow:2.0.0-alpha.7`

I see the recurring runs with a status:
![image](https://github.com/canonical/kfp-operators/assets/18201737/0fabab6d-2859-4d49-9e6b-80100cdc9101)

And the runs are actually scheduled:
![image](https://github.com/canonical/kfp-operators/assets/18201737/b9513588-e81c-4baa-87f7-b7dc5f22de25)

And these are the ClusterRoles and Bindings I've got in my cluster:

```
$ kubectl get clusterroles | grep admission
kubeflow-admission-webhook                                             2023-10-20T09:14:47Z
admission-webhook-kubeflow-poddefaults-view                            2023-10-20T09:17:53Z
admission-webhook-kubeflow-poddefaults-admin                           2023-10-20T09:17:53Z
admission-webhook-kubeflow-poddefaults-edit                            2023-10-20T09:17:53Z

$ kubectl get clusterrolebindings | grep admission
admission-webhook-kubeflow-admission-webhook             ClusterRole/kubeflow-admission-webhook                             28m
```

**Comment by emrahkyn** [comment]
@kimwnasptd I tried to provide the requested information here. Please note that all these information for kubeflow 1.7 running on k8s 1.28.

[admission-webhook-kubeflow-admission-webhook-clusterrolebinding.txt](https://github.com/canonical/kfp-operators/files/13112431/admission-webhook-kubeflow-admission-webhook-clusterrolebinding.txt)
[admission-webhook-logs.txt](https://github.com/canonical/kfp-operators/files/13112432/admission-webhook-logs.txt)
[admission-webhook-operator-logs.txt](https://github.com/canonical/kfp-operators/files/13112433/admission-webhook-operator-logs.txt)
[kubeflow-admission-webhook-clusterrole.txt](https://github.com/canonical/kfp-operators/files/13112434/kubeflow-admission-webhook-clusterrole.txt)

**Comment by emrahkyn** [comment]
@DnPlas I redeployed the environment on the lab having more resources and tested your workaround. I can confirm that the provided workaround worked very well for kubeflow 1.7 installed on both kubernetes 1.24.9 and 1.28. Thanks a lot for this, we could run the recurring runs now.

**Comment by NohaIhab** [comment]
After patching the ROCK and integrating it, recurring runs now work without the need for a workaround. To get the new rock you can do:
`juju refresh kfp-schedwf --channel=2.0-alpha.7/stable`
Note: the channel for kfp charms in 1.7 has changed from `2.0` to `2.0-alpha.7`. See [notice on discourse](https://discourse.charmhub.io/t/kfp-charms-from-charmed-kubeflow-1-7-migrated-to-channel-2-0-alpha-7/12381).
Thanks for filing the issue.
