### ISSUE TITLE
kfp-profile-controller's `crd_manifests.yaml.j2` incorrectly includes istio objects in `1.8-updates-dev-branch`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kfp-operators#373]
### Bug Description

on the `1.8-updates-dev-branch`, kfp-profile-controller's `crd_manifests.yaml.j2` includes references to istio `destinationrules` and `authorizationpolicies` objects.  This was introduced by #331 which updated the file to be more consistent with upstream.

These istio objects are intentionally omitted from charmed kubeflow because we don't currently use them in the kfp-profile-controller (see [our sync.py](https://github.com/canonical/kfp-operators/blob/464d70136a7e91c9fb8ef640c50d14ae2c7dfc20/charms/kfp-profile-controller/files/upstream/sync.py#L262)).  #331 introduced a bug in the form of the metacontroller having a dependency on istio.

To fix this, we can revert #331's changes to this file.  

### To Reproduce

-

### Environment

`1.8-updates-dev-branch`

### Relevant log output

```shell
-
```

**Comment by NohaIhab** [comment]
closed by #376
