### ISSUE TITLE
kfp-profile-controller's `crd_manifests.yaml.j2` incorrectly changes the controller `updateStrategy` to `OnDelete` for branch `1.8-updates-dev-branch`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kfp-operators#374]
### Bug Description

#331 updated the `crd_manifests.yaml.j2` DecoratorController on the `1.8-updates-dev-branch` to use `updateStrategy.method=OnDelete` for secrets (previously it was `InPlace`) ([ref](https://github.com/canonical/kfp-operators/commit/1c4975914708bf97b609d02672d2c6920944c849#diff-8f5a17efadcaacf2ed7078ffd59aacabbbddbb8bdb0653829911a32790b03976L10)).  `InPlace` meant that, if the desired value of the secret changed, the secret would be updated to reflect that, whereas `OnDelete` means the secret will only be updated if the old secret is deleted.  This is not desirable because we may change the secrets used for minio.

To fix this, we can revert to the previous `InPlace`.

Note: I am pretty sure about this above reasoning and proposal, but someone should check to confirm before implementing.  

### To Reproduce

-

### Environment

`1.8-updates-dev-branch`

### Relevant log output

```shell
-
```

**Comment by NohaIhab** [comment]
It was updated to `OnDelete` to align with upstream: https://github.com/kubeflow/manifests/blob/bb6b4b0c4763dfcace78a7c095ddf2c055b4c510/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml#L17

not sure what was the upstream decision there.
If we wish to diverge from upstream, we should add a comment with that in the yaml when implemented.
Will discuss with the team about the desired behavior.

**Comment by NohaIhab** [comment]
based on the team's discussion:
In Charmed Kubeflow, there's a config option in `minio` charm to change the secret (see in the [config.yaml](https://github.com/canonical/minio-operator/blob/main/config.yaml) of minio). Base on that, A secret object needs to be updated with the new value when the desired value of the secret is changed.

Conclusion: Let's revert the update strategy to `InPlace` and add a comment in the file with a note that we diverge from upstream.
