### ISSUE TITLE
Can not create pipeline from a file

### ISSUE THREAD

**Issue by eleblebici** [canonical/kfp-operators#466]
### Bug Description

I have deployed Charmed Kubeflow from channel 1.7/stable on Microk8s as it described [here](https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow). 

All the units are in active state: https://pastebin.ubuntu.com/p/KgXdc2N5rc/

All the pods are running: https://pastebin.ubuntu.com/p/fZfXjbRTqp/

I'm trying to create a new pipeline as it described [here](https://charmed-kubeflow.io/docs/explore-kubeflow#heading--kubeflow-pipeline).

I installed the pipeline compiler kfp version 1.8.0. I compiled the example pipeline given [here](https://raw.githubusercontent.com/canonical/kfp-operators/main/tests/integration/pipelines/sample_pipeline_execution_order.py).

At the pipeline creation page I am not able to create the pipeline by uploading the compiled yaml file. I'm attaching a screenshot. It hangs on this page.

![image](https://github.com/canonical/kfp-operators/assets/19303492/5e0fc6e0-af1e-42f2-8321-071c3709c2e0)

### To Reproduce

1- Follow the instructions shared [here](https://charmed-kubeflow.io/docs/get-started-with-charmed-kubeflow) but install the charmed kubeflow version 1.7
2- Try to create a pipeline from file as it described [here](https://charmed-kubeflow.io/docs/explore-kubeflow#heading--kubeflow-pipeline) 

### Environment

Juju version 3.4.2
Microk8s version 1.26 with classic confinement
Charmed Kubeflow 1.7/stable

### Relevant Log Output

```shell
I don't have any meaningfull logs. I also don't know exactly what to check. Please let me know if you need any container or juju logs.
```

**Comment by orfeas-k** [comment]
Hi there, not related to your specific issue, but CKF 1.7 is supported only by k8s <=1.24 and juju 2.9 as mentioned [here](https://charmed-kubeflow.io/docs/supported-versions). Could you redeploy with those requirements in mind and let us know if you hit the same issue?

**Comment by eleblebici** [comment]
> Hi there, not related to your specific issue, but CKF 1.7 is supported only by k8s <=1.24 and juju 2.9 as mentioned [here](https://charmed-kubeflow.io/docs/supported-versions). Could you redeploy with those requirements in mind and let us know if you hit the same issue? We also highly recommend deploying a newer version since 1.7 will go EOL when we release 1.9 in ~2 months.
> 
> EDIT: I also edited the tutorial to mention that for specific CKF versions, there are specific K8s and Juju requirements. LMK if you think this would help to avoid deploying with incompatible requirements in the future.

Thank you @orfeas-k for the prompt response. I tried that with Charmed Kubernetes version 1.24 and with juju version 3.4.0 (as I did not want to migrate the model to a newer version of juju controller for upgrading the CK to 1.8) and it worked. So, as you've already done, it will be useful to see the juju and Kubernetes version requirements in the tutorial. Thanks for the help!
