### ISSUE TITLE
`kfp-profile-controller` goes to error with uncaught exception when `custom_images` config is set incorrectly

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#485]
### Bug Description

`kfp-profile-controller` goes to error with an uncaught exception in the charm code when the `custom_images` config is set with a different image key than the one in [the default images json](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-profile-controller/src/default-custom-images.json).
The expected behavior is that [a warning  message gets logged](https://github.com/canonical/kfp-operators/blob/main/charms/kfp-profile-controller/src/charm.py#L240) and the new config is ignored.

This error can be hit frequently due to #484.

### To Reproduce

juju deploy kfp-profile-controller --trust --channel=2.0/stable

juju config kfp-profile-controller custom_images="visualization_server: 'gcr.io/ml-pipeline/visualization-server:2.0.3'
frontend_image: 'gcr.io/ml-pipeline/visualization-server:2.0.3'
"

# check juju status: charm goes to error
kfp-profile-controller/0*     error

### Environment

microk8s 1.25-strict/stable
juju 3.1/stable

### Relevant Log Output

```shell
unit-kfp-profile-controller-0: 10:41:16 ERROR unit.kfp-profile-controller/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 254, in <module>
    main(KfpProfileControllerOperator)
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/ops/main.py", line 429, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 102, in __init__
    self.images = self.get_images(
  File "./src/charm.py", line 240, in get_images
    self.log.warning(f"image_name {image_name} not in image list, ignoring.")
AttributeError: 'KfpProfileControllerOperator' object has no attribute 'log'
unit-kfp-profile-controller-0: 10:41:16 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-kfp-profile-controller-0: 10:41:16 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-kfp-profile-controller-0: 10:41:56 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-kfp-profile-controller-0: 10:41:57 INFO unit.kfp-profile-controller/0.juju-log Running legacy hooks/install.
unit-kfp-profile-controller-0: 10:41:57 ERROR unit.kfp-profile-controller/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 254, in <module>
    main(KfpProfileControllerOperator)
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/ops/main.py", line 429, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 102, in __init__
    self.images = self.get_images(
  File "./src/charm.py", line 240, in get_images
    self.log.warning(f"image_name {image_name} not in image list, ignoring.")
AttributeError: 'KfpProfileControllerOperator' object has no attribute 'log'
unit-kfp-profile-controller-0: 10:41:58 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by kimwnasptd** [comment]
100% agree that it shouldn't just go to error state with cryptic charm message. But in this case IMO the charm should go to blocked state, with a message saying that provided image keys are incorrect. 

So that it's super clear to users that they need to manually update the config to unblock the charm
