### ISSUE TITLE
Update `kfp-metadata-writer` manifests for `1.9.0-rc.2`

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#525]
### Context

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest.

### What needs to get done

[See the release handbook](https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg)

### Definition of Done

Manifests and images are updated to the corresponding version for `1.9.0-rc.2`

**Comment by misohu** [comment]
There were no changes form rc0 to rc2 important for this charm. You can find the diff [here](https://www.diffchecker.com/PiSNQebX/).
