### ISSUE TITLE
Update kfp manifests for 1.9.0

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#540]
### Context

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest

### What needs to get done

[See the release handbook](https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg)

### Definition of Done

Manifests and images are updated to the corresponding version for 1.9.0

**Comment by orfeas-k** [comment]
The only change that was introduced in kfp manifests between 1.9.0-rc.0 and 1.9.0 release is the [following](https://github.com/kubeflow/manifests/blob/473b1035304f847063ecaf0a44686182c437db64/apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml#L35-L38). However, our KFP Pods don't have an istio sidecar, thus we don't need any AuthorizationPolicy to configure the pod of KFP. Thus, we don't need to bring any changes to kfp.
