### ISSUE TITLE
Upgrade to KFP 2.3.0

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/kfp-operators#579]
### Context

This is primarily needed to resolve https://github.com/canonical/bundle-kubeflow/issues/1120

We will need to upgrade KFP to 2.3.0 and introduce some configurations in the `kfp-ui` charm, to ensure logs are persisted. The reason we need 2.3.0 is to ensure we include this fix https://github.com/kubeflow/pipelines/pull/11010

### What needs to get done

1. https://github.com/canonical/kfp-operators/issues/580
2. https://github.com/canonical/kfp-operators/issues/581
3. https://github.com/canonical/kfp-operators/issues/582
4. https://github.com/canonical/kfp-operators/issues/586
5. https://github.com/canonical/kfp-operators/issues/596
6. https://github.com/canonical/bundle-kubeflow/issues/1147
7. https://github.com/canonical/kfp-operators/issues/585
8. https://github.com/canonical/kfp-operators/issues/587
9. https://github.com/canonical/kfp-operators/issues/594

### Definition of Done

1. CKF bundle 1.9 is using KFP 2.3.0
2. All charms are released to the stable track for 2.3.0
3. https://github.com/canonical/bundle-kubeflow/issues/1120 is resolved

**Comment by kimwnasptd** [comment]
We expect this upgrade to be streamlined, as the manifests had minimal changes:
```bash
# cd kubeflow/pipelines
cd manifests/kustomize

git checkout 2.2.0
kustomize build env/cert-manager/platform-agnostic-multi-user > manifests-2-2-0.yaml

git checkout 2.3.0
kustomize build env/cert-manager/platform-agnostic-multi-user > manifests-2-3-0.yaml

diff manifests-2-2-0.yaml manifests-2-3-0.yaml
```

The above shows the following diff
```
2298d2297
<   - workflowtaskresults
3685c3684
<   appVersion: 2.3.0
---
>   appVersion: 2.2.0
4089c4088
<         image: gcr.io/ml-pipeline/cache-server:2.3.0
---
>         image: gcr.io/ml-pipeline/cache-server:2.2.0
4197c4196
<       - image: gcr.io/ml-pipeline/metadata-envoy:2.3.0
---
>       - image: gcr.io/ml-pipeline/metadata-envoy:2.2.0
4311c4310
<         image: gcr.io/ml-pipeline/metadata-writer:2.3.0
---
>         image: gcr.io/ml-pipeline/metadata-writer:2.2.0
4492c4491
<         image: gcr.io/ml-pipeline/api-server:2.3.0
---
>         image: gcr.io/ml-pipeline/api-server:2.2.0
4579c4578
<         image: gcr.io/ml-pipeline/persistenceagent:2.3.0
---
>         image: gcr.io/ml-pipeline/persistenceagent:2.2.0
4637c4636
<         image: gcr.io/ml-pipeline/scheduledworkflow:2.3.0
---
>         image: gcr.io/ml-pipeline/scheduledworkflow:2.2.0
4703,4707c4702
<         - name: FRONTEND_SERVER_NAMESPACE
<           valueFrom:
<             fieldRef:
<               fieldPath: metadata.namespace
<         image: gcr.io/ml-pipeline/frontend:2.3.0
---
>         image: gcr.io/ml-pipeline/frontend:2.2.0
4783c4778
<         image: gcr.io/ml-pipeline/viewer-crd-controller:2.3.0
---
>         image: gcr.io/ml-pipeline/viewer-crd-controller:2.2.0
4816c4811
<       - image: gcr.io/ml-pipeline/visualization-server:2.3.0
---
>       - image: gcr.io/ml-pipeline/visualization-server:2.2.0
4925c4920
<         - gcr.io/ml-pipeline/argoexec:v3.4.17-license-compliance
---
>         - gcr.io/ml-pipeline/argoexec:v3.4.16-license-compliance
4934c4929
<         image: gcr.io/ml-pipeline/workflow-controller:v3.4.17-license-compliance
---
>         image: gcr.io/ml-pipeline/workflow-controller:v3.4.16-license-compliance
```

**Comment by kimwnasptd** [comment]
Summary of the current state. We'll update KFP in CKF 1.9 to be 2.3. Alongside this bump there will be included:
1. https://github.com/canonical/bundle-kubeflow/issues/1120
2. https://github.com/canonical/kfp-operators/issues/584

Regarding KFP logs and when upgrading from KFP 2.2 to 2.3 the following will happen:
1. For KFP V2 Pipelines, the `logs` tab in the UI will now show the logs from new runs that will be created
2. V1 Pipelines will not be affected, as the logs from each step are exposed in the `Input/Output` tab of a step

The fastest way to detect if a run is for V1 or V2 is by inspecting the UI. The images from https://github.com/canonical/kfp-operators/issues/582#issuecomment-2500003055 will make it more clear how V1 and V2 runs (and Pipeline definitions) are shown in the UI

**Comment by NohaIhab** [comment]
KFP 2.3 is now integrated in CKF 1.9/stable, see the [announcement and upgrade instructions](https://discourse.charmhub.io/t/charmed-kubeflow-1-9-updated-to-use-kfp-2-3/16073)
