### ISSUE TITLE
Upgrade the rocks for 2.3.0

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/kfp-operators#581]
### Context

Follow-up of https://github.com/canonical/kfp-operators/issues/579

A more detailed list of the image tags can be seen in https://github.com/canonical/kfp-operators/issues/579#issuecomment-2473040282. The most interesting part is the fact that they are downgrading one minor version of Argo, which we'll need to understand why

### What needs to get done

1. Update the `rockcraft.yaml` files in https://github.com/canonical/pipelines-rocks/
2. Have a new branch to track this version
3. Publish the rocks

As a bonus point, we should see if we could also integrate the frontend image, which in the past was blocked by ISSUE

### Definition of Done

1. Rocks for 2.3.0 are published
2. the rockraft files are updated
3. The rocks are integrated into the updated charms

**Comment by NohaIhab** [comment]
added to the list:
https://github.com/canonical/pipelines-rocks/issues/153

Rock was blocked from building in 2.0 due to https://github.com/canonical/pipelines-rocks/issues/80, should now be unblocked in 2.3.0
