### ISSUE TITLE
Update the "1.8 to 1.9" upgrade guide to reference KFP 2.3

### ISSUE THREAD

**Issue by orfeas-k** [canonical/kfp-operators#585]
### Context

Update https://charmed-kubeflow.io/docs/upgrade-18-19 to reference KFP 2.3

### What needs to get done

Update doc

### Definition of Done

Doc is updated

**Comment by DnPlas** [comment]
[Guide](https://charmed-kubeflow.io/docs/upgrade-18-19) is now pointing to `2.3`. See the latest edit.
