### ISSUE TITLE
Create tracks for KFP 2.3.0

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/kfp-operators#586]
### Context

As part of #579 we need to create new `2.3/stable` and corresponding tracks to push the charms to.

This will also need to happen once we finalise the manifests updates from #583 

### What needs to get done

1. Create the new tracks in CharmHub
2. Create the new branches in GH

### Definition of Done

1. The charms can be published in the tracks

**Comment by DnPlas** [comment]
Tracks were created by @NohaIhab and charms are now published there, you can check in charmhub (https://charmhub.io/kfp-<charm-name>?channel=2.3/stable) or with `charmcraft status kfp-<charm name>`. Nothing else to do.
