### ISSUE TITLE
Announce the use of KFP 2.3 in a discourse post for CKF 1.9

### ISSUE THREAD

**Issue by orfeas-k** [canonical/kfp-operators#587]
### Context

Write a discourse post to announce that CKF 1.9 uses KFP 2.3

### What needs to get done

Write post

### Definition of Done

Post is published

**Comment by NohaIhab** [comment]
Announcement posted to [discourse](https://discourse.charmhub.io/t/charmed-kubeflow-1-9-updated-to-use-kfp-2-3/16073)
