### ISSUE TITLE
Release kfp-* charms to `2.3/stable`

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#596]
### Context

As part of #579 , after the upgrades are completed in `track/2.3` branch, we need to release all the kfp-* charms to `2.3/stable` channels

### What needs to get done

run the release [workflow dispatch](https://github.com/canonical/kfp-operators/actions/workflows/release.yaml) for each kfp charm from `2.3/edge` to `2.3/stable`

### Definition of Done

kfp-* charms are released to `2.3/stable`

**Comment by NohaIhab** [comment]
Note that due to changes in #582 `argo-controller` fix needs to be backported and promoted to `3.4/stable`

**Comment by DnPlas** [comment]
Charms are now released to their `2.3/stable` tracks. See https://charmhub.io/kfp-<name of charm>?channel=2.3/stable.
