### ISSUE TITLE
Make the kfp-api workload compatible with MySQL

### ISSUE THREAD

**Issue by shayancanonical** [canonical/kfp-operators#75]
`kfp-api` currently uses a [mariadb charm](https://charmhub.io/charmed-osm-mariadb-k8s), but we would like it to use our yet unpublished [mysql k8s charm](https://github.com/canonical/mysql-k8s-operator).

However, there exists an issue with the underlying `kfp-api` workload:
- There are tables created by the `kfp-api` workload that do not contain primary keys (in particular [default_experiments](https://github.com/kubeflow/pipelines/blob/5a56a9399908033ce97573abf85098fd77f649ae/backend/src/apiserver/model/default_experiment.go#L18) and [db_statuses](https://github.com/kubeflow/pipelines/blob/5a56a9399908033ce97573abf85098fd77f649ae/backend/src/apiserver/model/db_status.go#L18)).
- A [trusted source](https://lefred.be/content/mysql-group-replication-and-table-design/) explains why there can be no tables without primary keys (the `mysql` charm uses group replication even for a cluster with one node). Additionally, the [following bug](https://bugs.mysql.com/bug.php?id=83165) confirms that primary keys need to be defined.

Solutions:
1. Change upstream to define primary keys for the `db_statuses` and `default_experiments` tables ([associated issue](https://github.com/kubeflow/pipelines/issues/8014))
2. A workaround solution -> update the `kfp-api` operator to "pre" create the `mlpipeline` database and the `db_statuses` and `default_experiments` tables within it before starting the workload pod:
```
CREATE TABLE `db_statuses` (
  `HaveSamplesLoaded` tinyint(1) NOT NULL,
  PRIMARY KEY(`HaveSamplesLoaded`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `default_experiments` (
  `DefaultExperimentId` varchar(255) NOT NULL,
  PRIMARY KEY(`DefaultExperimentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by beliaev-maksim** [comment]
done
