### ISSUE TITLE
Example pipeline err - XGBoost - Iterative model training

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/kfp-operators#8]
![Screenshot from 2021-05-26 17-52-17](https://user-images.githubusercontent.com/27001378/119700460-25be8680-be4b-11eb-8bca-8e5f90261e54.png)

**Comment by knkski** [comment]
We use the PNS executor, and are thus hitting this issue: https://github.com/argoproj/argo-workflows/issues/1256

That is currently the best executor for us to use, so the best way to fix this is to just remove the failing sample pipelines for now, see #11
