### ISSUE TITLE
Example pipeline err - TFX - Taxi tip prediction model trainer 

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/kfp-operators#9]
![Screenshot from 2021-05-26 17-50-05](https://user-images.githubusercontent.com/27001378/119700195-d4ae9280-be4a-11eb-9f79-003e095bf67d.png)

**Comment by knkski** [comment]
Looks like this is an upstream issue: https://github.com/tensorflow/tfx/issues/1287 The easiest thing to do at the moment is to just remove the pipeline from the list of samples, see #11
